export enum WishlistRemoveConstant {
    REMOVE_WISHLIST_REQUEST = "REMOVE_WISHLIST_REQUEST",
    REMOVE_WISHLIST_SUCCESS = "REMOVE_WISHLIST_SUCCESS",
    REMOVE_WISHLIST_FAILURE = "REMOVE_WISHLIST_FAILURE"
}
